"""Banco de recursos. Todos os links foram conferidos por busca na web em out/2026.

Campos: id -> (trilha, papel, nome, link, tipo, custo, horas estimadas, nível)
papel = "Principal" (2 a 4 por trilha, item B do pedido) ou "Apoio" (documentação usada
em atividades específicas do cronograma).
"""

P, A = "Principal", "Apoio"
GRATIS = "Grátis"
CREDITOS = "Grátis ou por créditos do Google Skills (confira na página)"

RECURSOS = {
    # T01 Linguagens e ferramentas
    "R101": ("T01", P, "A Tour of Go", "https://go.dev/tour/", "Curso interativo", GRATIS, 6, "Iniciante"),
    "R102": ("T01", P, "Learn Go with Tests (Chris James)", "https://quii.gitbook.io/learn-go-with-tests", "Livro online + exercícios", GRATIS, 20, "Iniciante → Intermediário"),
    "R103": ("T01", P, "TypeScript Handbook (oficial)", "https://www.typescriptlang.org/docs/handbook/intro.html", "Documentação", GRATIS, 8, "Iniciante → Intermediário"),
    "R104": ("T01", P, "Pro Git, 2ª ed. (Chacon & Straub)", "https://git-scm.com/book/en/v2", "Livro online", GRATIS, 6, "Iniciante → Avançado"),
    "R105": ("T01", A, "Effective Go", "https://go.dev/doc/effective_go", "Documentação", GRATIS, 3, "Intermediário"),
    "R106": ("T01", A, "Go by Example", "https://gobyexample.com/", "Exemplos anotados", GRATIS, 4, "Iniciante → Intermediário"),
    "R107": ("T01", A, "GitHub Skills (cursos interativos)", "https://learn.github.com/skills", "Laboratório", GRATIS, 3, "Iniciante → Intermediário"),
    "R108": ("T01", A, "FastAPI: Tutorial - User Guide", "https://fastapi.tiangolo.com/tutorial/", "Documentação", GRATIS, 6, "Intermediário"),
    # T02 Bancos de dados
    "R201": ("T02", P, "PostgreSQL docs: cap. 13 Concurrency Control (MVCC, isolamento)", "https://www.postgresql.org/docs/current/mvcc.html", "Documentação", GRATIS, 5, "Intermediário"),
    "R202": ("T02", P, "PostgreSQL Exercises", "https://pgexercises.com/", "Laboratório", GRATIS, 8, "Iniciante → Avançado"),
    "R203": ("T02", P, "Use The Index, Luke (Markus Winand)", "https://use-the-index-luke.com/", "Livro online", GRATIS, 6, "Intermediário"),
    "R204": ("T02", A, "PostgreSQL docs: 13.3 Explicit Locking", "https://www.postgresql.org/docs/current/explicit-locking.html", "Documentação", GRATIS, 1, "Intermediário"),
    # T03 APIs e integrações
    "R301": ("T03", P, "Stripe: Designing robust and predictable APIs with idempotency", "https://stripe.com/blog/idempotency", "Artigo", GRATIS, 1, "Intermediário"),
    "R302": ("T03", P, "Amazon Builders' Library: Timeouts, retries and backoff with jitter", "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/", "Artigo", GRATIS, 1, "Intermediário"),
    "R303": ("T03", P, "Amazon Builders' Library: Making retries safe with idempotent APIs", "https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/", "Artigo", GRATIS, 1, "Intermediário"),
    "R304": ("T03", P, "Standard Webhooks: especificação", "https://github.com/standard-webhooks/standard-webhooks/blob/main/spec/standard-webhooks.md", "Especificação (repositório)", GRATIS, 1, "Intermediário"),
    # T04 Distribuídos / event-driven
    "R401": ("T04", P, "Designing Data-Intensive Applications, 2ª ed. (Kleppmann & Riccomini, 2026)", "https://dataintensive.net/", "Livro", "Pago (livro O'Reilly; veja biblioteca/assinatura)", 25, "Intermediário → Avançado"),
    "R402": ("T04", P, "microservices.io: Pattern: Transactional outbox", "https://microservices.io/patterns/data/transactional-outbox", "Artigo/padrão", GRATIS, 1, "Intermediário"),
    "R403": ("T04", P, "Pub/Sub: Exactly-once delivery", "https://docs.cloud.google.com/pubsub/docs/exactly-once-delivery", "Documentação", GRATIS, 2, "Intermediário"),
    "R404": ("T04", A, "microservices.io: Pattern: Saga", "https://microservices.io/patterns/data/saga.html", "Artigo/padrão", GRATIS, 1, "Intermediário"),
    "R405": ("T04", A, "Pub/Sub: Dead-letter topics", "https://cloud.google.com/pubsub/docs/handling-failures", "Documentação", GRATIS, 1, "Intermediário"),
    "R406": ("T04", A, "Pub/Sub: Order messages", "https://cloud.google.com/pubsub/docs/ordering", "Documentação", GRATIS, 1, "Intermediário"),
    # T05 Temporal
    "R501": ("T05", P, "Temporal 101: Introducing the Temporal Platform (Go ou Python)", "https://learn.temporal.io/courses/temporal_101/", "Curso hands-on", GRATIS, 2, "Iniciante"),
    "R502": ("T05", P, "Temporal 102: Exploring Durable Execution", "https://learn.temporal.io/courses/temporal_102/", "Curso hands-on", GRATIS, 4, "Intermediário"),
    "R503": ("T05", P, "Temporal: Versioning Workflows", "https://learn.temporal.io/courses/versioning", "Curso hands-on", GRATIS, 1.5, "Intermediário"),
    "R504": ("T05", P, "Temporal: Saga Pattern Made Easy", "https://temporal.io/blog/saga-pattern-made-easy", "Artigo", GRATIS, 1, "Intermediário"),
    "R505": ("T05", A, "Temporal: Go SDK developer guide", "https://docs.temporal.io/develop/go", "Documentação", GRATIS, 4, "Intermediário"),
    "R506": ("T05", A, "Temporal: Python SDK developer guide", "https://docs.temporal.io/develop/python", "Documentação", GRATIS, 3, "Intermediário"),
    "R507": ("T05", A, "Temporal Cloud: US$1,000 em créditos para novos usuários", "https://temporal.io/blog/get-usd1-000-in-free-credits-and-build-better-workflows-with-temporal-cloud", "Artigo (oferta)", "Créditos de teste (exige cartão)", 0.5, "—"),
    # T06 Arquitetura de domínio
    "R601": ("T06", P, "Architecture Patterns with Python / Cosmic Python (Percival & Gregory)", "https://www.cosmicpython.com/", "Livro online", GRATIS, 15, "Intermediário"),
    "R602": ("T06", P, "Learning Domain-Driven Design (Vlad Khononov, O'Reilly)", "https://www.oreilly.com/library/view/learning-domain-driven-design/9781098100124", "Livro", "Pago (O'Reilly)", 12, "Intermediário"),
    "R603": ("T06", P, "Wild Workouts (Go DDD/Clean/CQRS) + e-book Go With The Domain", "https://github.com/ThreeDotsLabs/wild-workouts-go-ddd-example", "Repositório + e-book", "Grátis (e-book via newsletter)", 10, "Intermediário → Avançado"),
    "R604": ("T06", P, "Martin Fowler: Strangler Fig", "https://martinfowler.com/bliki/StranglerFigApplication.html", "Artigo", GRATIS, 0.5, "Intermediário"),
    "R605": ("T06", A, "Martin Fowler: Parallel Change (expand/contract)", "https://martinfowler.com/bliki/ParallelChange.html", "Artigo", GRATIS, 0.5, "Intermediário"),
    "R606": ("T06", A, "Domain-Driven Design Reference (Eric Evans) e o 'blue book'", "https://www.domainlanguage.com/ddd/reference/", "Referência (PDF)", "Grátis (o livro completo é pago)", 3, "Intermediário"),
    "R607": ("T06", A, "DDD Crew: DDD Starter Modelling Process", "https://github.com/ddd-crew/ddd-starter-modelling-process", "Repositório/guia", GRATIS, 2, "Iniciante → Intermediário"),
    "R608": ("T06", A, "Go With The Domain (e-book da Three Dots Labs)", "https://threedots.tech/go-with-the-domain/", "E-book", "Grátis (via newsletter)", 8, "Intermediário"),
    # T07 Cloud/DevOps
    "R701": ("T07", P, "Google Skills (ex-Cloud Skills Boost): Develop Serverless Applications on Cloud Run", "https://www.cloudskillsboost.google/course_templates/741", "Laboratório (skill badge)", CREDITOS, 5.25, "Intermediário"),
    "R702": ("T07", P, "Cloud Build: Deploying to Cloud Run using Cloud Build", "https://docs.cloud.google.com/build/docs/deploying-builds/deploy-cloud-run", "Documentação", GRATIS, 2, "Intermediário"),
    "R703": ("T07", P, "Cloud SQL: Connect to Cloud SQL for PostgreSQL from Cloud Run (quickstart)", "https://docs.cloud.google.com/sql/docs/postgres/connect-instance-cloud-run", "Documentação/lab", "Grátis (recursos GCP consomem créditos)", 2, "Intermediário"),
    "R704": ("T07", P, "Google Skills: Build Infrastructure with Terraform on Google Cloud", "https://www.cloudskillsboost.google/course_templates/636", "Laboratório (skill badge)", CREDITOS, 5, "Intermediário (opcional)"),
    "R705": ("T07", A, "Cloud Run: Configure secrets for services (Secret Manager)", "https://docs.cloud.google.com/run/docs/configuring/services/secrets", "Documentação", GRATIS, 1, "Intermediário"),
    "R706": ("T07", A, "Google Cloud: créditos de US$300 e Free Tier", "https://cloud.google.com/free", "Página oficial", GRATIS, 0.5, "—"),
    "R707": ("T07", A, "Software Engineering at Google, cap. 24: Continuous Delivery", "https://abseil.io/resources/swe-book/html/ch24.html", "Livro online", GRATIS, 1.5, "Intermediário"),
    # T08 Confiabilidade/observabilidade
    "R801": ("T08", P, "Site Reliability Engineering (Google)", "https://sre.google/sre-book/table-of-contents/", "Livro online", GRATIS, 12, "Intermediário"),
    "R802": ("T08", P, "The Site Reliability Workbook (Google)", "https://sre.google/workbook/table-of-contents/", "Livro online", GRATIS, 8, "Intermediário"),
    "R803": ("T08", P, "OpenTelemetry Go: Getting Started by Example", "https://opentelemetry.io/docs/languages/go/getting-started/", "Documentação/tutorial", GRATIS, 3, "Intermediário"),
    "R804": ("T08", P, "Google Skills: Monitor and Log with Google Cloud Observability", "https://www.skills.google/course_templates/749", "Laboratório (skill badge)", CREDITOS, 4.25, "Iniciante → Intermediário"),
    "R805": ("T08", A, "PagerDuty Incident Response Documentation", "https://response.pagerduty.com/", "Guia", GRATIS, 2, "Intermediário"),
    "R806": ("T08", A, "PagerDuty Postmortem Documentation", "https://postmortems.pagerduty.com/", "Guia", GRATIS, 1.5, "Intermediário"),
    "R807": ("T08", A, "Testcontainers for Go: módulo Postgres", "https://golang.testcontainers.org/modules/postgres/", "Documentação", GRATIS, 1, "Intermediário"),
    "R808": ("T08", A, "Software Engineering at Google (livro completo, caps. de testes)", "https://abseil.io/resources/swe-book/html/toc.html", "Livro online", GRATIS, 6, "Intermediário"),
    "R809": ("T08", A, "Cloud Logging: Structured logging", "https://docs.cloud.google.com/logging/docs/structured-logging", "Documentação", GRATIS, 1, "Intermediário"),
    "R810": ("T08", A, "Cloud Trace overview", "https://docs.cloud.google.com/trace/docs/overview", "Documentação", GRATIS, 1, "Intermediário"),
    "R811": ("T08", A, "Cloud Monitoring: Alerting overview", "https://docs.cloud.google.com/monitoring/alerts", "Documentação", GRATIS, 1, "Intermediário"),
    "R812": ("T08", A, "Getting started with Testcontainers for Python", "https://testcontainers.com/guides/getting-started-with-testcontainers-for-python/", "Tutorial", GRATIS, 1, "Intermediário"),
    # T09 Dados/analytics
    "R901": ("T09", P, "Google Skills: Derive Insights from BigQuery Data", "https://www.cloudskillsboost.google/course_templates/623", "Laboratório (skill badge)", CREDITOS, 4, "Iniciante"),
    "R902": ("T09", P, "Google Skills: Build a Data Warehouse with BigQuery", "https://www.cloudskillsboost.google/course_templates/624", "Laboratório (skill badge)", CREDITOS, 5.25, "Intermediário"),
    "R903": ("T09", P, "dbt Fundamentals (dbt Learn)", "https://learn.getdbt.com/courses/dbt-fundamentals", "Curso", GRATIS, 5, "Iniciante → Intermediário"),
    "R904": ("T09", P, "dbt docs: Add data tests to your DAG", "https://docs.getdbt.com/docs/build/data-tests", "Documentação", GRATIS, 1.5, "Intermediário"),
    "R905": ("T09", A, "BigQuery sample dataset for Google Analytics ecommerce (GA4)", "https://developers.google.com/analytics/bigquery/web-ecommerce-demo-dataset", "Dataset público + docs", "Grátis (sandbox/free tier)", 1, "Intermediário"),
    "R906": ("T09", A, "Pub/Sub: BigQuery subscriptions", "https://docs.cloud.google.com/pubsub/docs/bigquery", "Documentação", GRATIS, 1, "Intermediário"),
    "R907": ("T09", A, "BigQuery sandbox (consultar sem cartão)", "https://cloud.google.com/blog/products/data-analytics/query-without-a-credit-card-introducing-bigquery-sandbox", "Artigo oficial", GRATIS, 0.5, "Iniciante"),
    "R908": ("T09", A, "Snowflake in 20 minutes (tutorial oficial)", "https://docs.snowflake.com/en/user-guide/getting-started-tutorial-log-in.html", "Tutorial", "Grátis (trial de 30 dias)", 1, "Iniciante (prioridade baixa)"),
    # T10 Integrações
    "R1001": ("T10", P, "Stripe: Build a subscriptions integration (Checkout)", "https://docs.stripe.com/billing/subscriptions/build-subscriptions", "Documentação/guia", "Grátis (modo de teste)", 4, "Intermediário"),
    "R1002": ("T10", P, "Stripe: Receive Stripe events in your webhook endpoint", "https://docs.stripe.com/webhooks", "Documentação", GRATIS, 2, "Intermediário"),
    "R1003": ("T10", P, "Airtable Web API: Introduction + Rate limits", "https://airtable.com/developers/web/api/introduction", "Documentação", "Grátis (plano Free: 1.000 chamadas/mês)", 3, "Intermediário"),
    "R1004": ("T10", P, "Airtable automation action: Run a script", "https://support.airtable.com/articles/6328053615-airtable-automation-action-run-a-script", "Documentação", GRATIS, 1, "Intermediário"),
    "R1005": ("T10", A, "Stripe: Test clocks", "https://docs.stripe.com/docs/billing/testing/test-clocks", "Documentação", GRATIS, 1, "Intermediário"),
    "R1006": ("T10", A, "Stripe: Test card numbers / testing", "https://docs.stripe.com/testing", "Documentação", GRATIS, 0.5, "Iniciante"),
    "R1007": ("T10", A, "Stripe: Payout reconciliation", "https://docs.stripe.com/payouts/reconciliation", "Documentação", GRATIS, 1, "Intermediário"),
    "R1008": ("T10", A, "Stripe: Using webhooks with subscriptions", "https://docs.stripe.com/billing/subscriptions/webhooks", "Documentação", GRATIS, 1, "Intermediário"),
    "R1009": ("T10", A, "Airtable Web API: Upload attachment", "https://airtable.com/developers/web/api/upload-attachment", "Documentação", GRATIS, 0.5, "Intermediário"),
    "R1010": ("T10", A, "Airtable Webhooks API overview", "https://support.airtable.com/docs/airtable-webhooks-api-overview", "Documentação", GRATIS, 1, "Intermediário"),
    "R1011": ("T10", A, "Airtable: Managing API call limits (limites por plano)", "https://support.airtable.com/docs/managing-api-call-limits-in-airtable", "Documentação", GRATIS, 0.5, "—"),
    "R1012": ("T10", A, "Healthie API docs (GraphQL)", "https://docs.gethealthie.com/", "Documentação", "Grátis para ler (sandbox depende de conta)", 2, "Intermediário (opcional)"),
    "R1013": ("T10", A, "PandaDoc API: Authentication overview (Dev Center/sandbox)", "https://developers.pandadoc.com/reference/auth-overview", "Documentação", "Grátis para ler (sandbox conforme plano)", 1, "Intermediário (opcional)"),
    "R1014": ("T10", A, "Amazon Cognito: Verifying JSON web tokens", "https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html", "Documentação", "Grátis para ler (free tier AWS)", 1, "Intermediário (opcional)"),
    "R1015": ("T10", A, "Stripe API: Idempotent requests", "https://docs.stripe.com/api/idempotent_requests", "Documentação", GRATIS, 0.5, "Intermediário"),
    "R1016": ("T10", A, "Stripe: Customer portal", "https://docs.stripe.com/customer-management", "Documentação", GRATIS, 1, "Intermediário"),
    # T11 IA aplicada
    "R1101": ("T11", P, "Vertex AI: Structured output (Gemini com response schema)", "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output", "Documentação", "Grátis para ler (uso consome créditos)", 2, "Intermediário"),
    "R1102": ("T11", P, "Document AI: Form Parser", "https://docs.cloud.google.com/document-ai/docs/form-parser", "Documentação", "Grátis para ler (uso consome créditos)", 2, "Intermediário"),
    "R1103": ("T11", P, "Google Skills: Automate Data Capture at Scale with Document AI", "https://www.cloudskillsboost.google/course_templates/674", "Laboratório (skill badge)", CREDITOS, 4, "Intermediário"),
    "R1104": ("T11", P, "Hamel Husain: Your AI Product Needs Evals", "https://hamel.dev/blog/posts/evals/index.html", "Artigo", GRATIS, 1.5, "Intermediário"),
    "R1105": ("T11", A, "Google Skills: Prompt Design in Vertex AI", "https://www.cloudskillsboost.google/course_templates/976", "Laboratório (skill badge)", GRATIS, 3.75, "Iniciante"),
    "R1106": ("T11", A, "Anthropic: Building effective agents", "https://www.anthropic.com/engineering/building-effective-agents", "Artigo", GRATIS, 1, "Intermediário"),
    "R1107": ("T11", A, "DOL: formulário WH-380-E (certificação médica FMLA, público)", "https://www.dol.gov/sites/dolgov/files/WHD/legacy/files/WH-380-E.pdf", "Formulário público (PDF)", GRATIS, 0.5, "—"),
    "R1108": ("T11", A, "DOL: FMLA forms", "https://www.dol.gov/agencies/whd/fmla/forms", "Página oficial", GRATIS, 0.5, "—"),
    # T12 Growth/frontend
    "R1201": ("T12", P, "Next.js Learn: Foundations (App Router, dashboard app)", "https://nextjs.org/learn/dashboard-app", "Curso interativo", GRATIS, 10, "Iniciante → Intermediário"),
    "R1202": ("T12", P, "Google Tag Manager: The data layer", "https://developers.google.com/tag-platform/tag-manager/datalayer", "Documentação", GRATIS, 1, "Intermediário"),
    "R1203": ("T12", P, "Trustworthy Online Controlled Experiments (Kohavi, Tang, Xu)", "https://experimentguide.com/", "Livro", "Pago (Cambridge University Press)", 10, "Intermediário"),
    "R1204": ("T12", P, "GrowthBook and Next.js (App Router)", "https://docs.growthbook.io/guide/nextjs-app-router", "Documentação (open source)", GRATIS, 2, "Intermediário"),
    "R1205": ("T12", A, "Google Analytics 4: Set up events", "https://developers.google.com/analytics/devguides/collection/ga4/events", "Documentação", GRATIS, 1, "Iniciante"),
    "R1206": ("T12", A, "GA4 Measurement Protocol", "https://developers.google.com/analytics/devguides/collection/protocol/ga4", "Documentação", GRATIS, 1.5, "Intermediário"),
    "R1207": ("T12", A, "Meta Conversions API: Using the API", "https://developers.facebook.com/documentation/ads-commerce/conversions-api/using-the-api", "Documentação", GRATIS, 1.5, "Intermediário (opcional)"),
    "R1208": ("T12", A, "Google Ads Help: About enhanced conversions", "https://support.google.com/google-ads/answer/9888656?hl=en", "Documentação", GRATIS, 0.5, "Intermediário (opcional)"),
    "R1209": ("T12", A, "Klaviyo: Events API overview", "https://developers.klaviyo.com/en/reference/events_api_overview", "Documentação", GRATIS, 1, "Intermediário (opcional)"),
    "R1210": ("T12", A, "VWO Developers", "https://developers.vwo.com", "Documentação", GRATIS, 1, "Intermediário (opcional)"),
    "R1211": ("T12", A, "Heyflow Help Center", "https://help.heyflow.com", "Documentação", GRATIS, 0.5, "Iniciante (opcional)"),
    # T13 Segurança/compliance
    "R1301": ("T13", P, "HHS: Summary of the HIPAA Security Rule", "https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html", "Guia oficial", GRATIS, 2, "Iniciante → Intermediário"),
    "R1302": ("T13", P, "HHS: Guidance on De-identification of PHI (Safe Harbor / Expert Determination)", "https://www.hhs.gov/hipaa/for-professionals/special-topics/de-identification/index.html", "Guia oficial", GRATIS, 2, "Intermediário"),
    "R1303": ("T13", P, "Google Cloud: HIPAA compliance on Google Cloud", "https://docs.cloud.google.com/docs/security/compliance/hipaa", "Documentação", GRATIS, 1.5, "Intermediário"),
    "R1304": ("T13", P, "OWASP API Security Top 10 (2023)", "https://owasp.org/API-Security/editions/2023/en/0x11-t10/", "Guia", GRATIS, 2, "Intermediário"),
    "R1305": ("T13", A, "Sensitive Data Protection overview (ex-DLP)", "https://docs.cloud.google.com/sensitive-data-protection/docs/sensitive-data-protection-overview", "Documentação", GRATIS, 1, "Intermediário"),
    "R1306": ("T13", A, "Cloud Audit Logs overview", "https://docs.cloud.google.com/logging/docs/audit", "Documentação", GRATIS, 1, "Intermediário"),
    "R1307": ("T13", A, "HHS: NPRM de atualização da Security Rule (fact sheet)", "https://www.hhs.gov/hipaa/for-professionals/security/hipaa-security-rule-nprm/factsheet/index.html", "Guia oficial", GRATIS, 0.5, "Intermediário"),
    # T14 AI-native
    "R1401": ("T14", P, "Claude Code docs: How Claude remembers your project (CLAUDE.md)", "https://code.claude.com/docs/en/memory", "Documentação", GRATIS, 1, "Intermediário"),
    "R1402": ("T14", P, "Anthropic: Best practices for Claude Code", "https://www.anthropic.com/engineering/claude-code-best-practices", "Guia", GRATIS, 1.5, "Intermediário"),
    "R1403": ("T14", P, "OpenAI Codex: Custom instructions with AGENTS.md", "https://developers.openai.com/codex/guides/agents-md", "Documentação", GRATIS, 1, "Intermediário"),
    "R1404": ("T14", P, "Anthropic Academy: Claude Code in Action", "https://anthropic.skilljar.com/claude-code-in-action", "Curso", GRATIS, 2, "Intermediário"),
    "R1405": ("T14", A, "Claude Code docs: Hooks reference", "https://code.claude.com/docs/en/hooks", "Documentação", GRATIS, 1, "Intermediário"),
    "R1406": ("T14", A, "Claude Code docs: Create custom subagents", "https://code.claude.com/docs/en/sub-agents", "Documentação", GRATIS, 1, "Intermediário"),
    "R1407": ("T14", A, "Claude Code docs: Configure permissions", "https://code.claude.com/docs/en/permissions", "Documentação", GRATIS, 0.5, "Intermediário"),
    "R1408": ("T14", A, "Import Linter (Python): layers contract", "https://import-linter.readthedocs.io/en/stable/contract_types/layers/", "Documentação", GRATIS, 0.5, "Intermediário"),
    "R1409": ("T14", A, "go-arch-lint (Go)", "https://pkg.go.dev/github.com/fe3dback/go-arch-lint", "Ferramenta/documentação", GRATIS, 0.5, "Intermediário"),
    "R1410": ("T14", A, "dependency-cruiser (TypeScript/JS)", "https://github.com/sverweij/dependency-cruiser", "Ferramenta/repositório", GRATIS, 0.5, "Intermediário"),
    "R1411": ("T14", A, "OpenAI Codex: Best practices", "https://developers.openai.com/codex/learn/best-practices", "Guia", GRATIS, 1, "Intermediário"),
    "R1412": ("T14", A, "AGENTS.md (formato aberto)", "https://agents.md/", "Especificação", GRATIS, 0.5, "Iniciante"),
    "R1413": ("T14", A, "OpenAI Cookbook: Using PLANS.md for multi-hour problem solving", "https://developers.openai.com/cookbook/articles/codex_exec_plans", "Guia", GRATIS, 1, "Intermediário"),
    # T15 Liderança/comunicação
    "R1501": ("T15", P, "Google Technical Writing (One e Two)", "https://developers.google.com/tech-writing", "Curso", GRATIS, 6, "Iniciante → Intermediário"),
    "R1502": ("T15", P, "Design Docs at Google (Malte Ubl)", "https://www.industrialempathy.com/posts/design-docs-at-google/", "Artigo", GRATIS, 0.5, "Intermediário"),
    "R1503": ("T15", P, "Lara Hogan: Feedback and performance resources (Feedback Equation)", "https://larahogan.me/resources/feedback/", "Guias/templates", GRATIS, 2, "Iniciante → Intermediário"),
    "R1504": ("T15", P, "Shape Up (Ryan Singer, Basecamp)", "https://basecamp.com/shapeup", "Livro online", GRATIS, 5, "Intermediário"),
    "R1505": ("T15", A, "ADR Templates (MADR, Nygard, Y-statements)", "https://adr.github.io/adr-templates/", "Templates", GRATIS, 0.5, "Iniciante"),
    "R1506": ("T15", A, "Lara Hogan: One-on-one meetings resources", "https://larahogan.me/resources/one-on-ones/", "Guias/templates", GRATIS, 1, "Iniciante"),
    "R1507": ("T15", A, "Google eng-practices: How to write code review comments", "https://google.github.io/eng-practices/review/reviewer/comments.html", "Guia", GRATIS, 0.5, "Iniciante → Intermediário"),
    "R1508": ("T15", A, "HBR: Performing a Project Premortem (Gary Klein)", "https://hbr.org/2007/09/performing-a-project-premortem", "Artigo", "Grátis/paywall parcial", 0.5, "Intermediário"),
    "R1509": ("T15", A, "GitLab Handbook: Communication (assíncrona/remota)", "https://handbook.gitlab.com/handbook/communication/", "Handbook", GRATIS, 1.5, "Intermediário"),
    "R1510": ("T15", A, "StaffEng: Staff Engineer (Will Larson)", "https://staffeng.com/book", "Livro/guias", "Guias grátis no site; livro pago", 4, "Intermediário → Avançado"),
    "R1511": ("T15", A, "Google eng-practices: Code review (guia completo)", "https://google.github.io/eng-practices/review/", "Guia", GRATIS, 2, "Intermediário"),
    # T16 Produto/ops/negócio
    "R1601": ("T16", P, "Paul Graham: Do Things that Don't Scale", "https://paulgraham.com/ds.html", "Ensaio", GRATIS, 0.5, "Iniciante"),
    "R1602": ("T16", P, "YC Startup School", "https://www.startupschool.org/", "Curso", GRATIS, 10, "Iniciante"),
    "R1603": ("T16", P, "DOL Fact Sheet #28G: Medical Certification under the FMLA (domínio)", "https://www.dol.gov/agencies/whd/fact-sheets/28g-fmla-serious-health-condition", "Guia oficial", GRATIS, 0.5, "Iniciante"),
    "R1604": ("T16", P, "YC Startup Library", "https://www.ycombinator.com/library", "Biblioteca (vídeos/ensaios)", GRATIS, 4, "Iniciante"),
    "R1605": ("T16", A, "DDD Crew: EventStorming glossary & cheat sheet", "https://github.com/ddd-crew/eventstorming-glossary-cheat-sheet", "Guia/repositório", GRATIS, 1, "Iniciante"),
    # T17 Inglês
    "R1701": ("T17", P, "EF SET (teste de inglês grátis, alinhado ao CEFR)", "https://www.efset.org/", "Teste", GRATIS, 1, "Todos"),
    "R1702": ("T17", P, "YouGlish (pronúncia em contexto real)", "https://youglish.com/", "Ferramenta", GRATIS, 10, "Todos"),
    "R1703": ("T17", P, "Rachel's English: Free American Accent Course", "https://rachelsenglish.com/free/", "Curso/vídeos", GRATIS, 10, "Intermediário"),
    "R1704": ("T17", P, "Tech Interview Handbook: Behavioral interviews", "https://www.techinterviewhandbook.org/behavioral-interview/", "Guia", GRATIS, 3, "Intermediário"),
    "R1705": ("T17", A, "Tech Interview Handbook: STAR format", "https://www.techinterviewhandbook.org/star-format", "Guia", GRATIS, 0.5, "Intermediário"),
    "R1706": ("T17", A, "Exponent Practice (mocks entre pares; antigo Pramp)", "https://www.tryexponent.com/blog/introducing-exponent-practice", "Plataforma", "Créditos grátis mensais + plano pago", 10, "Intermediário"),
    "R1707": ("T18", P, "Hello Interview: System Design Delivery Framework", "https://www.hellointerview.com/learn/system-design/in-a-hurry/delivery", "Guia", "Grátis (parte premium)", 2, "Intermediário"),
    "R1708": ("T18", P, "Tech Interview Handbook: Behavioral interviews for senior candidates", "https://www.techinterviewhandbook.org/behavioral-interview-senior-candidates/", "Guia", GRATIS, 1, "Intermediário"),
    "R1709": ("T17", A, "Software Engineering Daily (podcast técnico)", "https://softwareengineeringdaily.com/", "Podcast", GRATIS, 20, "Intermediário"),
    # T18 Carreira (item H)
    "R1801": ("T18", P, "Revelo: vagas remotas em empresas dos EUA para engenheiros da América Latina", "https://careers.revelo.com/", "Plataforma de vagas", GRATIS, 1, "—"),
    "R1802": ("T18", P, "Strider: vagas remotas para devs da América Latina", "https://onstrider.com/", "Plataforma de vagas", GRATIS, 1, "—"),
}
