"""Todos os tópicos das seções 3 (vaga) e 4 (checklist) do pedido, um por linha.

Cada tópico: (código, seção, grupo, tópico, trilha, prioridade, diagnóstico, como comprovar).
As semanas em que cada tópico é coberto NÃO são digitadas aqui: o gerador as calcula
a partir dos blocos do cronograma (cronograma.py), e falha se algum tópico ficar sem semana.
"""

S4 = "Seção 4 (checklist)"
S3 = "Seção 3 (vaga)"

E, R, O, B = "Essencial", "Recomendado", "Opcional", "Baixa"

TOPICOS = [
    # ---------------- Seção 4: checklist de qualificações ----------------
    # Linguagens e ferramentas
    ("LT01", S4, "Linguagens e ferramentas", "Python", "T01", E, "D01", "Serviços intake-legacy, ops-sync e form-filler no repositório + D01 refeito no CP"),
    ("LT02", S4, "Linguagens e ferramentas", "Go", "T01", E, "D02", "case-service, billing e orchestrator no repositório + D02 refeito no CP"),
    ("LT03", S4, "Linguagens e ferramentas", "TypeScript", "T01", R, "D03", "App Next.js + cliente tipado gerado do OpenAPI"),
    ("LT04", S4, "Linguagens e ferramentas", "SQL", "T02", E, "D04", "Migrações, queries operacionais/analíticas e modelos dbt"),
    ("LT05", S4, "Linguagens e ferramentas", "GitHub", "T01", E, "D05", "PRs com template, checks obrigatórios, issues e board do projeto"),
    ("LT06", S4, "Linguagens e ferramentas", "Controle de versão", "T01", E, "D05", "Histórico limpo, branches curtas, releases com tag e notas"),
    ("LT07", S4, "Linguagens e ferramentas", "Agile", "T15", R, "D05", "Ciclos semanais (estilo Shape Up), board, retros e checkpoints"),
    # Dados
    ("DA01", S4, "Dados", "PostgreSQL", "T02", E, "D04", "Schemas v1/v2, outbox, locks, índices e EXPLAIN no repositório"),
    ("DA02", S4, "Dados", "BigQuery", "T09", E, "D06", "Datasets raw/marts, assinatura Pub/Sub→BigQuery, queries versionadas"),
    ("DA03", S4, "Dados", "Snowflake (prioridade baixa: não aparece na vaga)", "T09", B, "D06", "Lab 'Snowflake in 20 minutes' + nota comparando com BigQuery"),
    ("DA04", S4, "Dados", "Sistemas de banco de dados", "T02", E, "D04", "Notas de DDIA/Postgres + ADR de isolamento/concorrência"),
    ("DA05", S4, "Dados", "Projetos de modelagem de dados", "T02", E, "D04", "ERD v1 (legado) × v2 (domínio) + modelo dimensional no dbt"),
    ("DA06", S4, "Dados", "Integração de gestão de dados", "T09", R, "D06", "Pipelines Postgres/Stripe/eventos→BigQuery + contrato de dados"),
    ("DA07", S4, "Dados", "Data analytics", "T09", R, "D06", "Análises de funil e tempo de ciclo em SQL"),
    ("DA08", S4, "Dados", "Business intelligence", "T09", R, "D06", "Dashboard Looker Studio de Ops/Growth"),
    ("DA09", S4, "Dados", "Tecnologias de análise de dados", "T09", R, "D06", "BigQuery + dbt + Looker Studio + export do GA4"),
    ("DA10", S4, "Dados", "Tomada de decisão orientada por dados", "T09", R, "D06", "Memos de decisão (experimento A/B, Form Filler, KPIs de Ops)"),
    ("DA11", S4, "Dados", "Verificações de qualidade de dados", "T09", E, "D06", "Testes dbt + comparadores de paridade/reconciliação no CI"),
    ("DA12", S4, "Dados", "Garantia da qualidade de dados", "T09", E, "D06", "Contratos de dados, validação estrita de mapeamentos, SLAs de frescor"),
    ("DA13", S4, "Dados", "Solução de problemas de dados", "T09", E, "D06", "Runbook de discrepâncias + RCA de incidentes de dados plantados"),
    # Engenharia e arquitetura
    ("EA01", S4, "Engenharia e arquitetura", "Engenharia de software", "T06", E, "D07", "Projeto LeaveFlow completo (código, testes, docs, operação)"),
    ("EA02", S4, "Engenharia e arquitetura", "Desenvolvimento de software", "T01", E, "D07", "Entregas incrementais semanais com demo"),
    ("EA03", S4, "Engenharia e arquitetura", "Implementação de software", "T01", E, "D07", "Features em staging/prd com release notes"),
    ("EA04", S4, "Engenharia e arquitetura", "Design de sistema", "T04", E, "D07", "Design docs + diagramas C4/sequência + mocks de system design"),
    ("EA05", S4, "Engenharia e arquitetura", "Design de aplicações", "T06", E, "D07", "Camadas Clean (domain/app/adapters) e APIs consistentes"),
    ("EA06", S4, "Engenharia e arquitetura", "Design de sistemas para o desenvolvimento de sistemas", "T06", E, "D07", "Rastreabilidade design doc → ADR → PR → release"),
    ("EA07", S4, "Engenharia e arquitetura", "Escalabilidade", "T04", R, "D07", "Teste de carga + relatório de capacidade (Cloud Run, pool, índices)"),
    ("EA08", S4, "Engenharia e arquitetura", "Sistemas distribuídos", "T04", E, "D08", "Outbox, Pub/Sub, consumidores idempotentes, sagas"),
    ("EA09", S4, "Engenharia e arquitetura", "Design orientado ao domínio (DDD)", "T06", E, "D07", "Context map, Bounded Context Canvas, agregados e eventos"),
    ("EA10", S4, "Engenharia e arquitetura", "Integração de sistemas", "T10", E, "D08", "Stripe, Airtable, Document AI/Gemini e legado integrados"),
    ("EA11", S4, "Engenharia e arquitetura", "Integrações de API", "T03", E, "D08", "Kit de integração (timeouts, retries, rate limit, assinatura)"),
    ("EA12", S4, "Engenharia e arquitetura", "Implementação do ciclo de vida do desenvolvimento de software (SDLC)", "T07", E, "D09", "Fluxo design→PR→CI→staging→prd→monitoramento documentado"),
    ("EA13", S4, "Engenharia e arquitetura", "Participação na fase de engenharia", "T15", R, "D07", "Design reviews escritos (ADRs) antes de implementar"),
    ("EA14", S4, "Engenharia e arquitetura", "Engenharia de projetos", "T15", R, "D14", "Plano da iniciativa de migração executado até produção"),
    ("EA15", S4, "Engenharia e arquitetura", "Aplicações de IA", "T11", E, "D15", "AI Form Filler com evals e revisão humana"),
    # Cloud, DevOps e operação
    ("CD01", S4, "Cloud, DevOps e operação", "Sistemas baseados em nuvem", "T07", E, "D09", "LeaveFlow rodando no GCP (staging/prd)"),
    ("CD02", S4, "Cloud, DevOps e operação", "Serviços serverless em nuvem", "T07", E, "D09", "Serviços e jobs no Cloud Run; badge de Cloud Run"),
    ("CD03", S4, "Cloud, DevOps e operação", "Engenharia de soluções em nuvem", "T07", R, "D09", "ADRs de arquitetura GCP com custo e trade-offs"),
    ("CD04", S4, "Cloud, DevOps e operação", "Automação de DevOps", "T07", E, "D09", "cloudbuild.yaml + infraestrutura reprodutível (gcloud/Terraform)"),
    ("CD05", S4, "Cloud, DevOps e operação", "Implementação de entrega contínua (CD)", "T07", E, "D09", "Deploy automático em staging e por tag em prd"),
    ("CD06", S4, "Cloud, DevOps e operação", "Implantação de sistemas", "T07", E, "D09", "Releases versionadas com rollback por revisão"),
    ("CD07", S4, "Cloud, DevOps e operação", "Implantação de aplicações", "T07", E, "D09", "Deploy de serviços Go/Python/Next.js"),
    ("CD08", S4, "Cloud, DevOps e operação", "Manutenção de aplicações", "T08", R, "D09", "Versionamento de workflows, migrações expand/contract, dependências"),
    ("CD09", S4, "Cloud, DevOps e operação", "Suporte a sistemas e aplicações", "T08", E, "D10", "Runbooks por alerta e de recuperação caso a caso"),
    ("CD10", S4, "Cloud, DevOps e operação", "Monitoramento em nuvem", "T08", E, "D09", "Cloud Monitoring/Logging/Trace configurados"),
    ("CD11", S4, "Cloud, DevOps e operação", "Monitoramento de sistemas de TI", "T08", E, "D09", "SLOs, alertas por burn rate e uptime checks"),
    # Confiabilidade e qualidade
    ("CQ01", S4, "Confiabilidade e qualidade", "Teste de software", "T08", E, "D10", "Unitários, integração (Testcontainers), contrato, e2e, replay"),
    ("CQ02", S4, "Confiabilidade e qualidade", "Feedback sobre código", "T15", E, "D13", "Revisões escritas dos PRs simulados do júnior e dos agentes"),
    ("CQ03", S4, "Confiabilidade e qualidade", "Revisão de garantia da qualidade", "T08", R, "D10", "Checklist de release/QA aplicado em cada release"),
    ("CQ04", S4, "Confiabilidade e qualidade", "Operações de controle de qualidade", "T08", R, "D10", "Gates de CI (lint, testes, arquitetura, evals, contratos)"),
    ("CQ05", S4, "Confiabilidade e qualidade", "Melhoria da qualidade", "T08", R, "D10", "Métricas antes/depois das correções sistêmicas"),
    ("CQ06", S4, "Confiabilidade e qualidade", "Identificação de problemas", "T08", E, "D10", "Alertas que detectam as falhas dos game days"),
    ("CQ07", S4, "Confiabilidade e qualidade", "Identificação de problemas de software", "T08", E, "D10", "Debug guiado por logs/traces documentado"),
    ("CQ08", S4, "Confiabilidade e qualidade", "Diagnóstico e solução de problemas", "T08", E, "D10", "Game days com timeline e mitigação"),
    ("CQ09", S4, "Confiabilidade e qualidade", "Solução de problemas técnicos", "T08", E, "D10", "Incidentes plantados resolvidos (DLQ, reconciliação, timezone)"),
    ("CQ10", S4, "Confiabilidade e qualidade", "Análise de falhas", "T08", E, "D10", "Postmortems blameless publicados"),
    ("CQ11", S4, "Confiabilidade e qualidade", "Análise de defeitos", "T08", R, "D10", "Registro e classificação de defeitos + análise de erros do Form Filler"),
    ("CQ12", S4, "Confiabilidade e qualidade", "Registro de problemas", "T08", R, "D10", "Issue tracker/incident log mantidos no repositório"),
    # Compliance
    ("CO01", S4, "Compliance", "Tratamento de informações confidenciais", "T13", E, "D11", "Classificação de dados, logs sem PHI, RBAC, auditoria, retenção"),
    # Operações e negócio
    ("OP01", S4, "Operações e negócio", "Gestão do fluxo de trabalho de operações", "T16", E, "D12", "Single Queue no Airtable com views por fila/SLA"),
    ("OP02", S4, "Operações e negócio", "Desenho de processos", "T16", R, "D12", "Mapas de processo as-is/to-be"),
    ("OP03", S4, "Operações e negócio", "Melhorias em processos empresariais", "T16", R, "D12", "Automação com métrica de tempo manual antes/depois"),
    ("OP04", S4, "Operações e negócio", "Iniciativas de excelência operacional", "T16", R, "D12", "Redução de falhas recorrentes após game days"),
    ("OP05", S4, "Operações e negócio", "Planejamento de ações estratégicas", "T15", R, "D14", "Plano ajustado pós-diagnóstico, avaliação de lacunas, plano 30-60-90"),
    ("OP06", S4, "Operações e negócio", "Implementação de iniciativas estratégicas", "T15", R, "D14", "Iniciativa de migração entregue"),
    ("OP07", S4, "Operações e negócio", "Tomada de decisão", "T15", E, "D14", "ADRs com alternativas e trade-offs"),
    ("OP08", S4, "Operações e negócio", "Gerenciamento de riscos do projeto", "T15", E, "D14", "Registro de riscos + premortem + comunicação de risco"),
    ("OP09", S4, "Operações e negócio", "Experiência em startups", "T16", E, "D12", "Simulada (ritmo semanal, cortes de escopo); lacuna real tratada em H"),
    # Liderança
    ("LI01", S4, "Liderança", "Liderança", "T15", E, "D13", "Artefatos de liderança semanais + simulações"),
    ("LI02", S4, "Liderança", "Liderança de equipe", "T15", E, "D13", "Brief de delegação e acompanhamento do 'júnior'"),
    ("LI03", S4, "Liderança", "Liderança em melhoria de desempenho", "T15", R, "D13", "Plano de crescimento do júnior simulado"),
    ("LI04", S4, "Liderança", "Coordenação de equipe", "T15", R, "D13", "Coordenação humano+agentes em fluxo multiagente"),
    ("LI05", S4, "Liderança", "Atribuição de tarefas", "T15", E, "D13", "Briefs de tarefa com critérios de pronto"),
    ("LI06", S4, "Liderança", "Priorização de tarefas", "T15", E, "D14", "Replanejamentos nos checkpoints com cortes explícitos"),
    ("LI07", S4, "Liderança", "Delegação", "T15", E, "D13", "Delegação do Form Filler (júnior) e de tarefas a agentes"),
    ("LI08", S4, "Liderança", "Coaching", "T15", R, "D13", "Mensagens de desbloqueio com perguntas de coaching"),
    ("LI09", S4, "Liderança", "Mentoria", "T15", R, "D13", "Onboarding doc + (real) mentoria de aluno/colega do CIn"),
    ("LI10", S4, "Liderança", "Mentoria para colaboradores juniores", "T15", E, "D13", "Revisões didáticas de PR + roteiros de 1:1"),
    ("LI11", S4, "Liderança", "Treinamento e mentoria da equipe", "T15", R, "D13", "Docs de padrão (integração, runbooks, dados sensíveis)"),
    # Gestão de projetos e comunicação
    ("PC01", S4, "Gestão de projetos e comunicação", "Escrita técnica", "T15", E, "D14", "Design docs, ADRs, runbooks, README"),
    ("PC02", S4, "Gestão de projetos e comunicação", "Elaboração de relatórios técnicos", "T15", E, "D14", "Postmortems, relatório de confiabilidade, avaliação de lacunas"),
    ("PC03", S4, "Gestão de projetos e comunicação", "Relatórios para partes interessadas", "T15", E, "D14", "Update semanal para 'CEO'/liderança"),
    ("PC04", S4, "Gestão de projetos e comunicação", "Relatórios para partes interessadas do projeto", "T15", R, "D14", "Status report da iniciativa de migração"),
    ("PC05", S4, "Gestão de projetos e comunicação", "Comunicação interna", "T15", E, "D14", "Updates diários escritos (em inglês)"),
    ("PC06", S4, "Gestão de projetos e comunicação", "Gerenciamento da comunicação do projeto", "T15", R, "D14", "Plano de comunicação (quem, o quê, quando)"),
    ("PC07", S4, "Gestão de projetos e comunicação", "Acompanhamento do progresso de projetos", "T15", E, "D14", "Coluna Status + board + demos semanais"),
    ("PC08", S4, "Gestão de projetos e comunicação", "Acompanhamento do cronograma do projeto", "T15", E, "D14", "Checkpoints a cada 4 semanas com horas reais × plano"),
    ("PC09", S4, "Gestão de projetos e comunicação", "Coordenação multidisciplinar de projetos", "T15", R, "D14", "Brief de experimento Eng+Growth+Ops"),
    ("PC10", S4, "Gestão de projetos e comunicação", "Colaboração multidisciplinar", "T15", R, "D14", "Simulações com Growth e Ops"),
    ("PC11", S4, "Gestão de projetos e comunicação", "Colaboração multifuncional", "T15", R, "D14", "Priorização de pedidos conflitantes Growth × Ops"),
    ("PC12", S4, "Gestão de projetos e comunicação", "Articulação com departamentos internos", "T15", R, "D14", "Alinhamento com Ops sobre mudanças no dia a dia"),
    ("PC13", S4, "Gestão de projetos e comunicação", "Interface com stakeholders", "T15", E, "D14", "Respostas escritas a pedidos de Growth/Ops"),
    ("PC14", S4, "Gestão de projetos e comunicação", "Colaboração com partes interessadas", "T15", R, "D14", "Brief do experimento construído com Growth"),
    ("PC15", S4, "Gestão de projetos e comunicação", "Comunicação com partes interessadas do projeto", "T15", E, "D14", "Comunicação de riscos e incidentes"),
    ("PC16", S4, "Gestão de projetos e comunicação", "Construção de relacionamentos com partes interessadas", "T15", R, "D14", "Rotina com 'clientes internos' (Ops/Growth)"),
    ("PC17", S4, "Gestão de projetos e comunicação", "Gestão de partes interessadas", "T15", R, "D14", "Mapa de stakeholders e plano de comunicação"),
    ("PC18", S4, "Gestão de projetos e comunicação", "Gestão de expectativas de partes interessadas", "T15", E, "D14", "Mensagens de atraso/escopo no formato da vaga"),
    # Idioma
    ("ID01", S4, "Idioma", "Inglês", "T17", E, "D17", "Vídeos semanais, EF SET inicial/final, mocks, docs em inglês"),

    # ---------------- Seção 3: vaga de referência ----------------
    # Natureza do cargo e responsabilidades
    ("VC01", S3, "Natureza do cargo", "Ciclo completo: build, debug, design, review, ship (90% construção)", "T01", E, "D07", "Demos e releases semanais do LeaveFlow"),
    ("VC02", S3, "Natureza do cargo", "Gerenciar diretamente um engenheiro júnior (prioridades, revisão, desbloqueio)", "T15", E, "D13", "Simulações de júnior (PRs, 1:1, desbloqueio, delegação)"),
    ("VC03", S3, "Natureza do cargo", "Dono da execução de engenharia de ponta a ponta (prioridades vêm da liderança)", "T15", E, "D14", "Planos semanais derivados de 'prioridades de negócio' simuladas"),
    ("VC04", S3, "Natureza do cargo", "Responsável por backend, orquestração de workflows, integrações e confiabilidade", "T04", E, "D08", "Serviços backend + Temporal + integrações + SLOs"),
    ("VC05", S3, "Natureza do cargo", "Dono do AI Form Filler (liderando o júnior responsável)", "T11", E, "D15", "Form Filler + brief de delegação + revisões"),
    ("VC06", S3, "Natureza do cargo", "Parceria com Growth (experimentos)", "T12", E, "D16", "Experimentos de preço/upsell e brief com Growth"),
    ("VC07", S3, "Natureza do cargo", "Parceria com Operations (automação)", "T16", E, "D12", "Single Queue e automações com Ops como cliente"),
    ("VC08", S3, "Natureza do cargo", "Entrar no frontend quando necessário", "T12", R, "D16", "Funil Next.js e console de revisão"),
    ("VC09", S3, "Natureza do cargo", "Impacto no negócio > sofisticação: solução confiável mais simples, entregue rápido", "T15", E, "D07", "ADRs 'quando NÃO usar' e cortes de escopo"),
    # Backend Systems & Reliability
    ("VB01", S3, "Backend Systems & Reliability", "Backend conecta intake, pagamentos, agendamento, operações clínicas, documentação médica, marketing de ciclo de vida e analytics", "T06", E, "D07", "Context map + fluxo de caso ponta a ponta"),
    ("VB02", S3, "Backend Systems & Reliability", "~9 serviços poliglotas no Cloud Run (Go, Python, TypeScript)", "T07", E, "D09", "6-7 serviços Go/Python/TS no Cloud Run"),
    ("VB03", S3, "Backend Systems & Reliability", "Workflows event-driven com Pub/Sub + Temporal Cloud", "T05", E, "D08", "Ponte Pub/Sub → sinais do Temporal"),
    ("VB04", S3, "Backend Systems & Reliability", "Duas instâncias Cloud SQL PostgreSQL", "T07", R, "D09", "ADR de topologia Cloud SQL (custo × isolamento)"),
    ("VB05", S3, "Backend Systems & Reliability", "BigQuery como camada analítica", "T09", E, "D06", "Datasets e marts no BigQuery"),
    ("VB06", S3, "Backend Systems & Reliability", "Ambientes de staging e produção por serviço", "T07", E, "D09", "Pipelines com staging automático e prd por tag"),
    ("VB07", S3, "Backend Systems & Reliability", "20+ integrações de terceiros", "T10", E, "D08", "Kit de integração reutilizado por todas as integrações"),
    ("VB08", S3, "Backend Systems & Reliability", "Features que falham com segurança (fail-safe)", "T08", E, "D10", "Design docs com modos de falha + flags de desligamento"),
    ("VB09", S3, "Backend Systems & Reliability", "Testes, monitoramento e CI/CD como salvaguardas contra falhas sistêmicas", "T08", E, "D10", "Gates de CI + alertas + rollback"),
    ("VB10", S3, "Backend Systems & Reliability", "Orquestração de workflows", "T05", E, "D08", "Workflow CaseLifecycle"),
    ("VB11", S3, "Backend Systems & Reliability", "APIs", "T03", E, "D02", "APIs REST com OpenAPI, erros padronizados e paginação"),
    ("VB12", S3, "Backend Systems & Reliability", "Pagamentos", "T10", E, "D08", "Integração Stripe (checkout, assinatura, estorno)"),
    ("VB13", S3, "Backend Systems & Reliability", "Gestão de estado", "T06", E, "D07", "Máquina de estados do agregado + estado do workflow"),
    ("VB14", S3, "Backend Systems & Reliability", "Retries", "T03", E, "D08", "Retries com backoff+jitter só em operações idempotentes"),
    ("VB15", S3, "Backend Systems & Reliability", "Idempotência", "T03", E, "D02", "Idempotency keys, inbox, dedupe por event id"),
    ("VB16", S3, "Backend Systems & Reliability", "Recuperação de falhas", "T08", E, "D08", "DLQ, replay, compensações, game days"),
    ("VB17", S3, "Backend Systems & Reliability", "Reconciliação de dados", "T09", E, "D06", "Jobs de reconciliação Stripe/Airtable/legado"),
    ("VB18", S3, "Backend Systems & Reliability", "Observabilidade", "T08", E, "D10", "Logs estruturados, métricas, tracing distribuído"),
    ("VB19", S3, "Backend Systems & Reliability", "Debugging em produção", "T08", E, "D10", "Exercício de debug só com logs/traces"),
    ("VB20", S3, "Backend Systems & Reliability", "Root-cause analysis", "T08", E, "D10", "RCAs em postmortems e incidentes de dados"),
    ("VB21", S3, "Backend Systems & Reliability", "Correções sistêmicas", "T08", E, "D10", "Ações sistêmicas implementadas após cada incidente"),
    ("VB22", S3, "Backend Systems & Reliability", "Automação: substituir workflows operacionais manuais por sistemas confiáveis", "T16", E, "D12", "Automações Airtable↔backend com métricas"),
    ("VB23", S3, "Backend Systems & Reliability", "Arquitetura event-driven com 20+ integrações", "T04", E, "D08", "Eventos versionados + integrações por eventos"),
    ("VB24", S3, "Backend Systems & Reliability", "Migração de modelo legado para novo modelo de domínio, lado a lado em produção", "T06", E, "D08", "Strangler fig com backfill, shadow read e cutover por coorte"),
    ("VB25", S3, "Backend Systems & Reliability", "DDD (padrão do código)", "T06", E, "D07", "Agregados, value objects e eventos de domínio"),
    ("VB26", S3, "Backend Systems & Reliability", "Clean Architecture", "T06", E, "D07", "Camadas + testes de arquitetura"),
    ("VB27", S3, "Backend Systems & Reliability", "CQRS", "T06", E, "D07", "Commands × queries separados onde paga"),
    ("VB28", S3, "Backend Systems & Reliability", "Sagas no Temporal", "T05", E, "D08", "Saga com compensações LIFO testadas"),
    ("VB29", S3, "Backend Systems & Reliability", "Transactional outbox", "T04", E, "D08", "Outbox + relay com SKIP LOCKED"),
    ("VB30", S3, "Backend Systems & Reliability", "Projeções", "T06", E, "D07", "Read models com rebuild por replay"),
    ("VB31", S3, "Backend Systems & Reliability", "Bounded contexts bem definidos", "T06", E, "D07", "Context map + canvases"),
    ("VB32", S3, "Backend Systems & Reliability", "Revisar trabalho com base nesses padrões e saber quando a solução mais simples é a certa", "T06", E, "D07", "ADRs de simplicidade + revisões de PR"),
    # Operations Systems (Airtable)
    ("VO01", S3, "Operations Systems (Airtable)", "Airtable como sistema operacional do time de Operations", "T10", E, "D12", "Base Single Queue desenhada com Ops como cliente"),
    ("VO02", S3, "Operations Systems (Airtable)", "Projeção de cada caso na Single Queue", "T10", E, "D08", "ops-sync projeta eventos → registros"),
    ("VO03", S3, "Operations Systems (Airtable)", "Consumir de volta no backend as mudanças de Ops via automações do Airtable", "T10", E, "D08", "Automação 'Run a script' → endpoint assinado"),
    ("VO04", S3, "Operations Systems (Airtable)", "Mapeamentos de campos", "T10", E, "D08", "Spec de mapeamento versionada + validação"),
    ("VO05", S3, "Operations Systems (Airtable)", "Rate limits", "T10", E, "D08", "Token bucket 5 req/s/base, lotes de 10, backoff em 429"),
    ("VO06", S3, "Operations Systems (Airtable)", "Anexos", "T10", E, "D08", "Upload de PDFs idempotente"),
    ("VO07", S3, "Operations Systems (Airtable)", "Replay de eventos sem sobrescrever edições manuais de Ops", "T10", E, "D08", "Propriedade por campo + replay com dry-run"),
    ("VO08", S3, "Operations Systems (Airtable)", "Recuperação de dados caso a caso", "T10", E, "D10", "CLI de replay por caso + runbook"),
    ("VO09", S3, "Operations Systems (Airtable)", "Integridade de campo: um campo errado gera um caso errado", "T10", E, "D11", "Testes de contrato que quebram o build"),
    # Growth Enablement
    ("VG01", S3, "Growth Enablement", "Parceria com Head of Growth e Frontend Growth Engineer", "T12", R, "D16", "Briefs e relatórios de experimento"),
    ("VG02", S3, "Growth Enablement", "Experimentos de funil, preço, checkout, assinatura e upsell", "T12", R, "D16", "Experimentos A/B de preço e upsell"),
    ("VG03", S3, "Growth Enablement", "Analytics e conversion tracking", "T12", R, "D16", "Plano de tracking + GA4/GTM"),
    ("VG04", S3, "Growth Enablement", "Instrumentação de canais de anúncios", "T12", R, "D16", "Conversões server-side (GA4 MP, Meta CAPI, Google Ads)"),
    ("VG05", S3, "Growth Enablement", "Infraestrutura para testar, aprender e entregar com dados confiáveis", "T12", R, "D16", "Bucketing determinístico, SRM check, reconciliação de eventos"),
    # Engineering Leadership
    ("VL01", S3, "Engineering Leadership", "Documentar problema, abordagem e plano antes de implementar", "T15", E, "D14", "Design docs antes de cada fase"),
    ("VL02", S3, "Engineering Leadership", "Update diário conciso (progresso, funciona, não funciona, próximos passos)", "T15", E, "D14", "Updates diários em inglês"),
    ("VL03", S3, "Engineering Leadership", "Prioridades de negócio → planos técnicos simples com trade-offs (velocidade, escopo, qualidade)", "T15", E, "D14", "Planos quinzenais com trade-offs explícitos"),
    ("VL04", S3, "Engineering Leadership", "Compromissos realistas e aviso precoce de risco (o que aconteceu, o que muda, novo prazo)", "T15", E, "D14", "Mensagens de risco nos checkpoints"),
    # AI-Native Engineering
    ("VA01", S3, "AI-Native Engineering", "Entrega via sessões supervisionadas de Claude Code e Codex", "T14", E, "D15", "Log de sessões e revisões de agentes"),
    ("VA02", S3, "AI-Native Engineering", "Regras no nível do repositório", "T14", E, "D15", "CLAUDE.md/AGENTS.md versionados com changelog"),
    ("VA03", S3, "AI-Native Engineering", "Guardrails", "T14", E, "D15", "Permissões, hooks, deny lists e evals como gate"),
    ("VA04", S3, "AI-Native Engineering", "Testes de arquitetura", "T14", E, "D15", "go-arch-lint / import-linter / dependency-cruiser no CI"),
    ("VA05", S3, "AI-Native Engineering", "Fluxos multiagente", "T14", E, "D15", "Planner/implementer/reviewer e testes adversariais"),
    ("VA06", S3, "AI-Native Engineering", "Planejar, delegar, revisar e verificar de forma independente o trabalho dos agentes", "T14", E, "D15", "docs/agent-reviews.md com defeitos pegos"),
    # Expectativas 30-60-90
    ("V301", S3, "Expectativas 30-60-90", "30d: entregar o projeto pago em produção", "T10", E, "D14", "Releases com checkout pago (test mode) em prd"),
    ("V302", S3, "Expectativas 30-60-90", "30d: entender os codebases e explicar como um caso flui de ponta a ponta", "T06", E, "D07", "Doc + vídeo 'como um caso flui'"),
    ("V303", S3, "Expectativas 30-60-90", "30d: diagnosticar e resolver incidentes sozinho", "T08", E, "D10", "Game days resolvidos sozinho com timeline"),
    ("V304", S3, "Expectativas 30-60-90", "30d: assumir planejamento, acompanhamento, releases e comunicação escrita", "T15", E, "D14", "Runbook de release + updates + planos"),
    ("V305", S3, "Expectativas 30-60-90", "30d: avaliação escrita de lacunas (arquitetura, confiabilidade, execução) e o que corrigir primeiro", "T15", E, "D14", "Documento de avaliação de lacunas"),
    ("V306", S3, "Expectativas 30-60-90", "30d: compromissos sem surpresas", "T15", E, "D14", "Checkpoints com previsão × realizado"),
    ("V307", S3, "Expectativas 30-60-90", "60d: dono das prioridades, direção técnica, revisões e entregas do júnior", "T15", E, "D13", "Brief de delegação + revisões do júnior"),
    ("V308", S3, "Expectativas 30-60-90", "60d: entregar melhorias da avaliação de lacunas", "T08", E, "D10", "3 correções sistêmicas entregues"),
    ("V309", S3, "Expectativas 30-60-90", "60d: liderar iniciativa grande a partir de objetivo de negócio (restrições, limites, alternativas, plano até produção)", "T15", E, "D14", "Plano e execução da migração"),
    ("V310", S3, "Expectativas 30-60-90", "60d: eliminar problemas recorrentes com correções sistêmicas", "T08", E, "D10", "Ações de postmortem fechadas"),
    ("V311", S3, "Expectativas 30-60-90", "60d: propor melhorias antes de pedirem", "T15", R, "D14", "Lista de propostas não pedidas"),
    ("V312", S3, "Expectativas 30-60-90", "90d: engenharia mais rápida/confiável que a herdada; melhorias mensuráveis (Growth, Ops, confiabilidade, cliente)", "T08", E, "D10", "Métricas antes/depois por release"),
    ("V313", S3, "Expectativas 30-60-90", "90d: alavancagem via sistemas, ferramentas, agentes de IA, documentação e delegação", "T14", E, "D15", "Harness de agentes + docs + delegação medidos"),
    ("V314", S3, "Expectativas 30-60-90", "90d: júnior mais efetivo", "T15", R, "D13", "Onboarding doc + revisões didáticas"),
    ("V315", S3, "Expectativas 30-60-90", "90d: identificar oportunidades de alto valor não pedidas", "T15", R, "D12", "3 propostas com impacto estimado"),
    ("V316", S3, "Expectativas 30-60-90", "90d: elevar o padrão de execução (simplicidade, ciclos rápidos, releases seguros, comunicação, accountability)", "T15", R, "D14", "Retrospectiva final com métricas de execução"),
    # Requisitos
    ("VR01", S3, "Requisitos", "7+ anos de engenharia de software", "T15", E, "—", "Não se cobre com estudo: ver análise de distância (H)"),
    ("VR02", S3, "Requisitos", "2+ anos sendo dono de sistemas event-driven em produção", "T04", E, "D08", "Lacuna real; projeto é proxy, ver H"),
    ("VR03", S3, "Requisitos", "Experiência em startups ou ambientes rápidos", "T16", E, "D12", "Lacuna real; simulação + vagas intermediárias (H)"),
    ("VR04", S3, "Requisitos", "Forte em APIs, webhooks, bancos de dados, integrações e sistemas event-driven", "T03", E, "D08", "Kit de integração, Stripe, Airtable, outbox"),
    ("VR05", S3, "Requisitos", "Capaz de trabalhar no full stack quando necessário", "T12", R, "D16", "Next.js funil + console"),
    ("VR06", S3, "Requisitos", "Já liderou ou fez mentoria de engenheiros", "T15", E, "D13", "Simulações + mentoria real recomendada (H)"),
    ("VR07", S3, "Requisitos", "Cuidado instintivo com dados sensíveis (ambiente regulado ou disciplina equivalente)", "T13", E, "D11", "Práticas estilo HIPAA no projeto"),
    ("VR08", S3, "Requisitos", "Uso intenso de agentes de IA no dia a dia", "T14", E, "D15", "Labs AI-native semanais"),
    ("VR09", S3, "Requisitos", "Ownership extremo; Growth e Ops como clientes (observar fluxos antes de automatizar)", "T16", E, "D12", "Job stories e mapa as-is antes de automatizar"),
    ("VR10", S3, "Requisitos", "Alta accountability; preferir entregar valor a construir algo teoricamente perfeito", "T15", E, "D14", "Cortes de escopo documentados nos checkpoints"),
    # Diferenciais
    ("VD01", S3, "Diferenciais", "Feature com LLM + human-in-the-loop no ar (onde falhou, o que aprendeu, como melhorou)", "T11", R, "D15", "Doc de falhas/melhorias do Form Filler com evals"),
    ("VD02", S3, "Diferenciais", "Sistemas de pagamento e assinatura em produção", "T10", R, "D08", "Stripe test mode completo (lacuna: não é produção real)"),
    ("VD03", S3, "Diferenciais", "Workflow engines (Temporal, Cadence, Step Functions)", "T05", R, "D08", "Temporal 101/102/Versioning + CaseLifecycle"),
    ("VD04", S3, "Diferenciais", "Engenharia com HIPAA e manipulação de PHI em produção", "T13", R, "D11", "Controles estilo HIPAA com dados fictícios (lacuna: não é PHI real)"),
    # Cultura e condições
    ("VK01", S3, "Cultura e condições", "Aprender rápido e decidir bem", "T15", E, "—", "Checkpoints com replanejamento baseado em evidência"),
    ("VK02", S3, "Cultura e condições", "Trabalhar muito e ser profissional (inclui 60+ h/semana com frequência)", "T16", E, "—", "Decisão pessoal informada (H); plano não simula 60 h"),
    ("VK03", S3, "Cultura e condições", "Foco em resultado de negócio", "T16", E, "D12", "Métricas de negócio nos memos e demos"),
    ("VK04", S3, "Cultura e condições", "Alta integridade", "T15", E, "—", "Postmortems honestos; candidatura sem exageros"),
    ("VK05", S3, "Cultura e condições", "Perfil: velocidade > arquitetura de longo prazo, requisitos ambíguos, manter sistemas existentes, generalista", "T16", E, "—", "Migração do legado + trabalho em várias áreas"),
    ("VK06", S3, "Cultura e condições", "Remoto com 8h de sobreposição com 8h-18h ET e alta disponibilidade para incidentes", "T08", E, "—", "Game days + rotina de horário alinhada a ET"),
    ("VK07", S3, "Cultura e condições", "Inglês fluente obrigatório", "T17", E, "D17", "Trilha de inglês + vídeos + mocks"),
    ("VK08", S3, "Cultura e condições", "Remuneração e condições (US$120-140k, folga flexível, bônus): negociação e modelo de contratação", "T16", R, "—", "Pesquisa de faixa, PJ/contractor × EOR (semana 24)"),
    # Stack
    ("VS01", S3, "Stack", "Go", "T01", E, "D02", "Serviços Go"),
    ("VS02", S3, "Stack", "Python", "T01", E, "D01", "Serviços Python"),
    ("VS03", S3, "Stack", "PostgreSQL", "T02", E, "D04", "Cloud SQL/Postgres local"),
    ("VS04", S3, "Stack", "TypeScript", "T01", R, "D03", "Cliente TS + Next.js"),
    ("VS05", S3, "Stack", "Next.js", "T12", R, "D16", "web/ (funil + console)"),
    ("VS06", S3, "Stack", "GCP", "T07", E, "D09", "Projeto GCP com budget alerts"),
    ("VS07", S3, "Stack", "Cloud Run", "T07", E, "D09", "Serviços/jobs no Cloud Run"),
    ("VS08", S3, "Stack", "Cloud SQL", "T07", E, "D09", "Instância Postgres gerenciada"),
    ("VS09", S3, "Stack", "Pub/Sub", "T04", E, "D08", "Tópicos, assinaturas, DLQ"),
    ("VS10", S3, "Stack", "BigQuery", "T09", E, "D06", "Datasets e marts"),
    ("VS11", S3, "Stack", "Cloud Build", "T07", E, "D09", "cloudbuild.yaml"),
    ("VS12", S3, "Stack", "Temporal Cloud", "T05", E, "D08", "Worker conectado ao Temporal (Cloud trial ou dev server)"),
    ("VS13", S3, "Stack", "Vertex AI (Gemini)", "T11", E, "D15", "Extração com structured output"),
    ("VS14", S3, "Stack", "Google Document AI", "T11", E, "D15", "Form Parser no pipeline"),
    ("VS15", S3, "Stack", "Stripe", "T10", E, "D08", "billing/"),
    ("VS16", S3, "Stack", "Healthie", "T10", O, "D08", "Adapter de agendamento por interface (fake + docs GraphQL)"),
    ("VS17", S3, "Stack", "PandaDoc", "T10", O, "D08", "Envio para assinatura via sandbox ou fake"),
    ("VS18", S3, "Stack", "AWS Cognito", "T10", O, "D11", "Auth de staff no console (JWT verificado)"),
    ("VS19", S3, "Stack", "Airtable", "T10", E, "D08", "Single Queue + ops-sync"),
    ("VS20", S3, "Stack", "Webflow", "T12", O, "D16", "Integração formulário externo → webhook de intake"),
    ("VS21", S3, "Stack", "Heyflow", "T12", O, "D16", "Integração formulário externo → webhook de intake"),
    ("VS22", S3, "Stack", "Klaviyo", "T12", O, "D16", "Eventos de ciclo de vida (conta grátis ou fake)"),
    ("VS23", S3, "Stack", "VWO", "T12", O, "D16", "Comparação comprar × construir para experimentos"),
    ("VS24", S3, "Stack", "Google Tag Manager", "T12", R, "D16", "dataLayer + container GTM"),
    ("VS25", S3, "Stack", "Google Analytics", "T12", R, "D16", "GA4 + Measurement Protocol + export BQ"),
    ("VS26", S3, "Stack", "Google Ads", "T12", O, "D16", "Conversões offline/enhanced (conceito + gclid)"),
    ("VS27", S3, "Stack", "Meta (Ads / Conversions API)", "T12", O, "D16", "CAPI em modo teste com dedupe por event_id"),
    ("VS28", S3, "Stack", "Claude Code", "T14", E, "D15", "CLAUDE.md, hooks, subagentes"),
    ("VS29", S3, "Stack", "Codex", "T14", E, "D15", "AGENTS.md, PLANS.md"),
    ("VS30", S3, "Stack", "Harnesses de agentes no nível do repositório", "T14", E, "D15", "Regras + hooks + testes + evals versionados"),
    # Perguntas da candidatura
    ("VQ01", S3, "Perguntas da candidatura", "Q1 What interested you in this role?", "T17", E, "D17", "Resposta final na aba Candidatura"),
    ("VQ02", S3, "Perguntas da candidatura", "Q2 Why do you think you're a strong fit?", "T17", E, "D17", "Resposta final na aba Candidatura"),
    ("VQ03", S3, "Perguntas da candidatura", "Q3 Hardest part of this role for you, and why?", "T17", E, "D17", "Resposta final na aba Candidatura"),
    ("VQ04", S3, "Perguntas da candidatura", "Q4 Production system owned end-to-end (metric, what broke, what changed)", "T17", E, "D17", "Resposta final na aba Candidatura"),
    ("VQ05", S3, "Perguntas da candidatura", "Q5 Vídeo: most technically challenging thing you've personally built", "T17", E, "D17", "Vídeo final ≤3 min"),
    ("VQ06", S3, "Perguntas da candidatura", "Q6 Time you cut scope to hit a deadline", "T17", E, "D17", "Resposta final na aba Candidatura"),
    ("VQ07", S3, "Perguntas da candidatura", "Q7 How do you use AI in your engineering workflow today?", "T17", E, "D17", "Resposta final + doc 'How I use AI'"),
]
