"""Trilhas de estudo, em ordem de dependência (fundamentos antes de padrões avançados)."""

# id: (nome, objetivo, nível-alvo, prioridade, depende de, o que pular se atrasar)
TRILHAS = {
    "T00": (
        "Diagnóstico e setup",
        "Medir o nível real em cada grupo de tópicos e montar o ambiente (GCP com alertas de custo, repositório, ferramentas).",
        "—",
        "Essencial",
        "—",
        "Nada: é o que calibra o resto. Se faltar tempo, adie D16 (Growth) para a semana 2.",
    ),
    "T01": (
        "Linguagens e ferramentas (Go, Python, TypeScript, Git/GitHub)",
        "Escrever Go e Python idiomáticos para serviços de produção; TypeScript suficiente para Next.js e clientes tipados; fluxo Git/GitHub profissional.",
        "Go e Python: intermediário-avançado; TypeScript: intermediário; Git/GitHub: avançado",
        "Essencial (TypeScript: recomendado)",
        "T00",
        "Capítulos avançados de Learn Go with Tests (reflection, generics avançado); GitHub Skills além de review/merge conflicts.",
    ),
    "T02": (
        "Bancos de dados, SQL e modelagem (PostgreSQL)",
        "Modelar dados transacionais, dominar transações/isolamento/locks, índices e EXPLAIN, migrações seguras.",
        "Intermediário-avançado",
        "Essencial",
        "T01",
        "CTEs recursivas e exercícios avançados do pgexercises; leitura completa do Use The Index, Luke (fique nos capítulos de B-tree e WHERE).",
    ),
    "T03": (
        "APIs, webhooks e integrações (HTTP, idempotência, retries, rate limits)",
        "Construir APIs e consumidores de APIs/webhooks que toleram duplicatas, timeouts, 429 e quedas de terceiros.",
        "Avançado",
        "Essencial",
        "T01, T02",
        "Circuit breaker próprio (use biblioteca) e a versão Python completa do kit (faça só o cliente com retries).",
    ),
    "T04": (
        "Sistemas distribuídos e arquitetura event-driven (Pub/Sub, outbox)",
        "Entender garantias de entrega, ordenação e consistência; implementar outbox, consumidores idempotentes e DLQ.",
        "Intermediário-avançado",
        "Essencial",
        "T02, T03",
        "Capítulos de DDIA sobre consenso/replicação (leia transações, codificação e streams primeiro).",
    ),
    "T05": (
        "Orquestração de workflows (Temporal, sagas)",
        "Modelar processos de longa duração com Temporal: sinais, timers, retries, sagas com compensação, testes de replay e versionamento.",
        "Intermediário-avançado",
        "Essencial",
        "T04",
        "Deploy em Temporal Cloud (mantenha dev server local + vídeo); worker Python separado (use só Go).",
    ),
    "T06": (
        "Arquitetura de domínio (DDD, Clean Architecture, CQRS, projeções, migração lado a lado)",
        "Desenhar bounded contexts, agregados e eventos; aplicar Clean/CQRS onde pagam; revisar trabalho com esses padrões e saber quando simplificar; migrar legado com strangler fig.",
        "Intermediário-avançado (capaz de revisar)",
        "Essencial",
        "T04 (pode começar em paralelo com T05)",
        "Livro pago de DDD (use o DDD Reference gratuito + Cosmic Python); rebuild de projeções com versionamento.",
    ),
    "T07": (
        "Cloud GCP e DevOps (Cloud Run, Cloud SQL, Cloud Build, CI/CD)",
        "Colocar serviços em staging/produção com pipeline automatizado, segredos, contas de serviço mínimas e custo controlado.",
        "Intermediário",
        "Essencial",
        "T01",
        "Terraform (use gcloud scriptado e documente); badge de Terraform.",
    ),
    "T08": (
        "Confiabilidade, testes e observabilidade (SRE, incidentes, RCA)",
        "Testar em camadas, observar (logs, métricas, traces), definir SLOs/alertas, responder a incidentes e fazer correções sistêmicas.",
        "Intermediário-avançado",
        "Essencial",
        "T07",
        "Teste de carga elaborado (faça um cenário simples); badge de observabilidade.",
    ),
    "T09": (
        "Dados, analytics e qualidade (BigQuery, dbt, reconciliação, BI)",
        "Levar eventos para o BigQuery, modelar marts, testar qualidade de dados, reconciliar fontes e apoiar decisões com dashboards.",
        "Intermediário",
        "Essencial (BI e Snowflake: recomendado/baixa)",
        "T02, T04",
        "Snowflake; badge 'Build a Data Warehouse'; dashboard sofisticado (um painel simples basta).",
    ),
    "T10": (
        "Integrações do domínio (Stripe, Airtable; Healthie, PandaDoc, Cognito)",
        "Integrar pagamentos/assinaturas e o sistema operacional de Ops (Airtable) com idempotência, reconciliação, rate limits, anexos e replays seguros.",
        "Avançado em Stripe e Airtable; familiaridade nas demais",
        "Essencial (Healthie, PandaDoc, Cognito: opcional)",
        "T03, T04, T05",
        "Healthie, PandaDoc e Cognito (deixe como adapters fake por interface); customer portal do Stripe.",
    ),
    "T11": (
        "IA aplicada (Document AI, Gemini, human-in-the-loop, evals)",
        "Construir e operar o 'AI Form Filler': extração estruturada, validação, revisão humana, evals e melhoria contínua.",
        "Intermediário",
        "Essencial (é o produto que o cargo lidera)",
        "T05, T10",
        "Comparação Document AI × Gemini (escolha um); envio para assinatura via PandaDoc.",
    ),
    "T12": (
        "Growth engineering e frontend (Next.js, A/B, tracking, anúncios)",
        "Construir funil e experimentos confiáveis, instrumentar conversões client/server-side e analisar resultados com rigor.",
        "Intermediário",
        "Recomendado",
        "T01 (TypeScript), T09",
        "Klaviyo, VWO, Webflow/Heyflow (leitura apenas); Meta CAPI (fique com GA4 Measurement Protocol).",
    ),
    "T13": (
        "Segurança e compliance (estilo HIPAA, PHI, acesso, auditoria)",
        "Tratar dados sensíveis por padrão: classificação, mínimo necessário, logs sem PHI, RBAC, auditoria, retenção e pseudonimização.",
        "Intermediário",
        "Essencial",
        "T07",
        "Sensitive Data Protection (use hashing com sal); threat model formal (faça a versão leve).",
    ),
    "T14": (
        "Engenharia AI-native (Claude Code, Codex, guardrails, testes de arquitetura, multiagente)",
        "Planejar, delegar, revisar e verificar de forma independente o trabalho de agentes, com regras e guardrails versionados no repositório.",
        "Avançado",
        "Essencial",
        "T00 (contínua; aprofunda junto com T06/T08)",
        "Comparação Claude Code × Codex em toda tarefa (escolha um como principal e use o outro 1×/semana).",
    ),
    "T15": (
        "Liderança, gestão de projetos e comunicação (~10% do tempo técnico)",
        "Escrever e planejar bem, delegar e mentorar um júnior, gerir stakeholders e expectativas, comunicar riscos cedo.",
        "Intermediário (simulado) com evidência escrita",
        "Essencial",
        "— (contínua, semanal)",
        "Leituras longas; mantenha sempre os artefatos (update, design doc, comunicação de risco).",
    ),
    "T16": (
        "Produto, operações e negócio (processos, automação de Ops, startup)",
        "Tratar Growth e Ops como clientes: observar fluxos, mapear processos, automatizar com métrica de impacto e pensar como startup.",
        "Intermediário",
        "Recomendado",
        "—",
        "YC Startup School completo (fique no ensaio do Paul Graham e na biblioteca).",
    ),
    "T17": (
        "Inglês técnico e entrevistas (1h/dia, fora das 4h técnicas)",
        "Falar com fluência sobre o trabalho técnico, responder perguntas comportamentais em STAR e escrever docs/updates em inglês.",
        "C1 funcional para entrevistas (meta a calibrar no diagnóstico)",
        "Essencial",
        "—",
        "Nunca pule o vídeo semanal; se atrasar, troque o podcast por shadowing curto.",
    ),
    "T18": (
        "Carreira e candidatura (semanas 23-24)",
        "Transformar o plano em candidatura: portfólio, respostas, mocks de entrevista, mercado e modelo de contratação.",
        "Pronto para processos de vagas intermediárias",
        "Essencial",
        "Todas",
        "Post técnico público (deixe para depois das candidaturas piloto).",
    ),
    "FLEX": (
        "Reforço flex (alocado pelo diagnóstico)",
        "Horas reservadas para reforçar as trilhas com pior resultado no diagnóstico e nos checkpoints.",
        "—",
        "—",
        "—",
        "É o primeiro buffer a ser consumido quando houver atraso.",
    ),
}
